/**
 * Curated "starter" decks for learning the basics — added from the Study tab and
 * used to seed new installs. Defined as plain data; `presetToDeck` stamps fresh
 * ids and SRS state so a copy is fully owned by the user. Verse texts are the
 * World English Bible (public domain), fetched verbatim from the app's own
 * scripture source.
 */

import { uid } from '@/lib/util/id';

import type { Card, CardRef, Deck, DeckKind } from './types';

export type PresetCard = { front: string; back: string; ref?: CardRef };

export type PresetLevel = 'basics' | 'intermediate' | 'advanced';

export type PresetDeck = {
  key: string;
  title: string;
  kind: DeckKind;
  level: PresetLevel;
  description: string;
  cards: PresetCard[];
};

export const PRESET_LEVELS: { key: PresetLevel; label: string }[] = [
  { key: 'basics', label: 'Basics' },
  { key: 'intermediate', label: 'Going deeper' },
  { key: 'advanced', label: 'Advanced' },
];

export const PRESET_DECKS: PresetDeck[] = [
  // --- Basics ---------------------------------------------------------------
  {
    key: 'bible-basics',
    title: 'Bible Basics',
    kind: 'fact',
    level: 'basics',
    description: 'Big-picture facts about the Bible itself.',
    cards: [
      { front: 'How many books are in the whole Bible?', back: '66 — 39 Old Testament, 27 New Testament' },
      { front: 'What are the first five books of the Bible called?', back: 'The Pentateuch (the Law / Torah)' },
      { front: 'What is the first book of the Bible?', back: 'Genesis' },
      { front: 'What is the shortest verse in the Bible?', back: '“Jesus wept.” (John 11:35)' },
      { front: 'What is the longest chapter in the Bible?', back: 'Psalm 119' },
      { front: 'What language was most of the Old Testament written in?', back: 'Hebrew' },
      { front: 'What language was the New Testament written in?', back: 'Greek' },
    ],
  },
  {
    key: 'ot-books',
    title: 'Books of the Old Testament',
    kind: 'fact',
    level: 'basics',
    description: 'Find your way around the Old Testament.',
    cards: [
      { front: 'How many books are in the Old Testament?', back: '39' },
      { front: 'Name the five books of the Law (Pentateuch).', back: 'Genesis, Exodus, Leviticus, Numbers, Deuteronomy' },
      { front: 'What is the longest book of the Bible?', back: 'Psalms (150 chapters)' },
      { front: 'Which OT books are called the “wisdom books”?', back: 'Job, Psalms, Proverbs, Ecclesiastes, Song of Songs' },
      { front: 'What is the last book of the Old Testament?', back: 'Malachi' },
      { front: 'Which book tells of Israel’s escape from Egypt?', back: 'Exodus' },
      { front: 'Which two OT books are named after women?', back: 'Ruth and Esther' },
      { front: 'Which book comes right after the Pentateuch and tells of entering the Promised Land?', back: 'Joshua' },
      { front: 'Which four books are the “major prophets”… plus one of tears?', back: 'Isaiah, Jeremiah (+ his Lamentations), Ezekiel, Daniel' },
      { front: 'What single book records Israel’s songbook of prayer and praise?', back: 'Psalms' },
    ],
  },
  {
    key: 'nt-books',
    title: 'Books of the New Testament',
    kind: 'fact',
    level: 'basics',
    description: 'Find your way around the New Testament.',
    cards: [
      { front: 'How many books are in the New Testament?', back: '27' },
      { front: 'Name the four Gospels.', back: 'Matthew, Mark, Luke, and John' },
      { front: 'Which book records the acts of the early church?', back: 'Acts' },
      { front: 'Who wrote most of the New Testament letters?', back: 'Paul' },
      { front: 'What is the last book of the Bible?', back: 'Revelation' },
      { front: 'Which Gospel writer was a physician?', back: 'Luke' },
      { front: 'Which is the longest of Paul’s letters?', back: 'Romans' },
      { front: 'What three letters are named for their recipients Timothy and Titus called?', back: 'The Pastoral Epistles' },
    ],
  },
  {
    key: 'key-people',
    title: 'Key People of the Bible',
    kind: 'fact',
    level: 'basics',
    description: 'The major figures of the biblical story.',
    cards: [
      { front: 'Who built an ark to survive the flood?', back: 'Noah' },
      { front: 'Who led Israel out of slavery in Egypt?', back: 'Moses' },
      { front: 'Which shepherd boy became king and wrote many psalms?', back: 'David' },
      { front: 'Who was the wisest king of Israel?', back: 'Solomon' },
      { front: 'Who was unharmed in the lions’ den?', back: 'Daniel' },
      { front: 'Who was swallowed by a great fish?', back: 'Jonah' },
      { front: 'Who was the mother of Jesus?', back: 'Mary' },
      { front: 'Who baptized Jesus in the Jordan River?', back: 'John the Baptist' },
      { front: 'Who was the first man God created?', back: 'Adam' },
      { front: 'To whom did God promise descendants as numerous as the stars?', back: 'Abraham' },
    ],
  },
  {
    key: 'apostles',
    title: 'The Twelve Apostles',
    kind: 'fact',
    level: 'basics',
    description: 'Get to know the twelve men Jesus called.',
    cards: [
      { front: 'Which apostle was a tax collector?', back: 'Matthew (also called Levi)' },
      { front: 'Who walked on water toward Jesus?', back: 'Peter' },
      { front: 'Who is called “the disciple whom Jesus loved”?', back: 'John' },
      { front: 'Which apostle doubted until he saw the risen Jesus?', back: 'Thomas' },
      { front: 'Who replaced Judas Iscariot among the Twelve?', back: 'Matthias (Acts 1:26)' },
      { front: 'Who betrayed Jesus for thirty pieces of silver?', back: 'Judas Iscariot' },
      { front: 'Which two brothers, sons of Zebedee, were among the Twelve?', back: 'James and John' },
      { front: 'What did Jesus nickname James and John?', back: 'Boanerges — “Sons of Thunder”' },
      { front: 'Who brought his brother Simon Peter to Jesus?', back: 'Andrew' },
      { front: 'Which apostle is also known as Nathanael?', back: 'Bartholomew' },
      { front: 'Which apostle was called “the Zealot”?', back: 'Simon the Zealot' },
      { front: 'What trade did Peter, Andrew, James, and John share?', back: 'They were fishermen' },
      { front: 'Who asked Jesus, “Show us the Father”?', back: 'Philip' },
    ],
  },
  {
    key: 'life-of-jesus',
    title: 'The Life of Jesus',
    kind: 'fact',
    level: 'basics',
    description: 'The story of Jesus from Bethlehem to the ascension.',
    cards: [
      { front: 'Where was Jesus born?', back: 'Bethlehem' },
      { front: 'In what town did Jesus grow up?', back: 'Nazareth' },
      { front: 'Who was Jesus’ earthly (adoptive) father?', back: 'Joseph, a carpenter' },
      { front: 'Who baptized Jesus, and in what river?', back: 'John the Baptist, in the Jordan' },
      { front: 'How long was Jesus tempted in the wilderness?', back: '40 days and 40 nights' },
      { front: 'About how old was Jesus when he began his ministry?', back: 'About 30 (Luke 3:23)' },
      { front: 'How many disciples did Jesus choose as apostles?', back: 'Twelve' },
      { front: 'What meal did Jesus share with his disciples the night he was betrayed?', back: 'The Last Supper (Passover)' },
      { front: 'Where did Jesus pray before his arrest?', back: 'The Garden of Gethsemane' },
      { front: 'Who sentenced Jesus to be crucified?', back: 'Pontius Pilate' },
      { front: 'What is the name of the place where Jesus was crucified?', back: 'Golgotha — “the place of a skull” (Calvary)' },
      { front: 'On which day did Jesus rise from the dead?', back: 'The third day — the first day of the week (Sunday)' },
      { front: 'How many days passed between the resurrection and the ascension?', back: '40 days (Acts 1:3)' },
    ],
  },
  {
    key: 'ten-commandments',
    title: 'The Ten Commandments',
    kind: 'fact',
    level: 'basics',
    description: 'The law given at Sinai — and how Jesus summed it up.',
    cards: [
      { front: 'Where in the Bible are the Ten Commandments listed?', back: 'Exodus 20 (and again in Deuteronomy 5)' },
      { front: 'On what mountain did Moses receive the commandments?', back: 'Mount Sinai' },
      { front: 'What is the first commandment?', back: '“You shall have no other gods before me.”' },
      { front: 'Which commandment tells us to rest one day in seven?', back: 'Remember the Sabbath day, to keep it holy (4th)' },
      { front: 'Which commandment comes with a promise about long life?', back: 'Honor your father and your mother (5th)' },
      { front: 'What were the commandments written on?', back: 'Two stone tablets, written by the finger of God' },
      { front: 'What did Jesus call the greatest commandment?', back: 'Love the Lord your God with all your heart, soul, and mind' },
      { front: 'And the second greatest?', back: 'Love your neighbor as yourself' },
      { front: 'What is the last commandment?', back: 'You shall not covet' },
      { front: 'What did Moses do with the tablets when he saw the golden calf?', back: 'He threw them down and broke them (Exodus 32)' },
    ],
  },
  {
    key: 'foundation-verses',
    title: 'Foundation Verses',
    kind: 'verse',
    level: 'basics',
    description: 'Ten bedrock verses to hide in your heart (WEB).',
    cards: [
      { front: 'Genesis 1:1', back: 'In the beginning, God created the heavens and the earth.', ref: { bookId: 1, chapter: 1, verse: 1 } },
      { front: 'Psalm 23:1', back: 'Yahweh is my shepherd: I shall lack nothing.', ref: { bookId: 19, chapter: 23, verse: 1 } },
      { front: 'Joshua 1:9', back: 'Haven’t I commanded you? Be strong and courageous. Don’t be afraid. Don’t be dismayed, for Yahweh your God is with you wherever you go.', ref: { bookId: 6, chapter: 1, verse: 9 } },
      { front: 'Isaiah 41:10', back: 'Don’t you be afraid, for I am with you. Don’t be dismayed, for I am your God. I will strengthen you. Yes, I will help you. Yes, I will uphold you with the right hand of my righteousness.', ref: { bookId: 23, chapter: 41, verse: 10 } },
      { front: 'Matthew 6:33', back: 'But seek first God’s Kingdom, and his righteousness; and all these things will be given to you as well.', ref: { bookId: 40, chapter: 6, verse: 33 } },
      { front: 'Romans 3:23', back: 'For all have sinned, and fall short of the glory of God.', ref: { bookId: 45, chapter: 3, verse: 23 } },
      { front: 'Romans 6:23', back: 'For the wages of sin is death, but the free gift of God is eternal life in Christ Jesus our Lord.', ref: { bookId: 45, chapter: 6, verse: 23 } },
      { front: 'Romans 8:28', back: 'We know that all things work together for good for those who love God, to those who are called according to his purpose.', ref: { bookId: 45, chapter: 8, verse: 28 } },
      { front: 'Ephesians 2:8', back: 'For by grace you have been saved through faith, and that not of yourselves; it is the gift of God.', ref: { bookId: 49, chapter: 2, verse: 8 } },
      { front: '1 John 1:9', back: 'If we confess our sins, he is faithful and righteous to forgive us the sins, and to cleanse us from all unrighteousness.', ref: { bookId: 62, chapter: 1, verse: 9 } },
    ],
  },

  // --- Going deeper ----------------------------------------------------------
  {
    key: 'miracles',
    title: 'Miracles of Jesus',
    kind: 'fact',
    level: 'intermediate',
    description: 'Signs and wonders from the Gospels.',
    cards: [
      { front: 'What was Jesus’ first recorded miracle?', back: 'Turning water into wine at Cana (John 2)' },
      { front: 'How many men did Jesus feed with five loaves and two fish?', back: 'About 5,000 (plus women and children)' },
      { front: 'Whom did Jesus raise after four days in the tomb?', back: 'Lazarus' },
      { front: 'What did Jesus calm with a word on the sea?', back: 'A storm — the wind and the waves' },
      { front: 'Whose mother-in-law did Jesus heal of a fever?', back: 'Peter’s' },
      { front: 'How many lepers did Jesus heal at once — and how many returned to thank him?', back: 'Ten healed; one returned (a Samaritan)' },
      { front: 'How long had the woman who touched Jesus’ garment been bleeding?', back: 'Twelve years' },
      { front: 'Whose daughter did Jesus raise with the words “Talitha cumi”?', back: 'Jairus’ (a synagogue ruler)' },
      { front: 'What happened when the disciples fished where Jesus told them?', back: 'A miraculous catch — nets full to breaking' },
      { front: 'Whose ear did Jesus heal in Gethsemane?', back: 'Malchus’, the high priest’s servant' },
    ],
  },
  {
    key: 'parables',
    title: 'Parables of Jesus',
    kind: 'fact',
    level: 'intermediate',
    description: 'The stories Jesus told — and what they mean.',
    cards: [
      { front: 'In the parable of the sower, what do the four soils represent?', back: 'Ways of receiving the word — the path, rocky ground, thorns, and good soil' },
      { front: 'Which parable answers “Who is my neighbor?”', back: 'The Good Samaritan (Luke 10)' },
      { front: 'In the Prodigal Son, what does the father do when he sees his son returning?', back: 'Runs to him, embraces him, and celebrates his return' },
      { front: 'A shepherd leaves how many sheep to find the one that is lost?', back: 'Ninety-nine' },
      { front: 'What grows from the tiny mustard seed in Jesus’ parable?', back: 'The kingdom of God — a tree the birds nest in' },
      { front: 'In the parable of the talents, what did the third servant do with his?', back: 'Buried it in the ground' },
      { front: 'What happened to the man who built his house on sand?', back: 'It fell when the storm came — unlike the house on the rock' },
      { front: 'In the parable of the unforgiving servant, how often did Jesus say to forgive?', back: 'Seventy times seven' },
      { front: 'Who prayed “God, be merciful to me, a sinner” — and went home justified?', back: 'The tax collector, not the Pharisee (Luke 18)' },
      { front: 'In the parable of the great banquet, who ends up filling the seats?', back: 'The poor, crippled, blind, and lame — gathered from the streets' },
    ],
  },
  {
    key: 'exodus-journey',
    title: 'The Exodus',
    kind: 'fact',
    level: 'intermediate',
    description: 'From slavery in Egypt to the edge of the Promised Land.',
    cards: [
      { front: 'How many plagues did God send on Egypt?', back: 'Ten' },
      { front: 'What was the first plague?', back: 'The Nile turned to blood' },
      { front: 'What was the last plague?', back: 'The death of the firstborn — Israel spared by the Passover lamb’s blood' },
      { front: 'What sea did Israel cross on dry ground?', back: 'The Red Sea' },
      { front: 'What bread from heaven fed Israel in the wilderness?', back: 'Manna' },
      { front: 'How did God lead Israel through the wilderness?', back: 'A pillar of cloud by day and fire by night' },
      { front: 'What idol did Israel make while Moses was on Sinai?', back: 'A golden calf' },
      { front: 'How many spies scouted Canaan — and how many brought a good report?', back: 'Twelve; only Joshua and Caleb' },
      { front: 'How many years did Israel wander in the wilderness?', back: 'Forty' },
      { front: 'Who led Israel into the Promised Land after Moses died?', back: 'Joshua' },
    ],
  },
  {
    key: 'kings-israel',
    title: 'Kings & the Divided Kingdom',
    kind: 'fact',
    level: 'intermediate',
    description: 'From Saul to the exile — Israel’s royal history.',
    cards: [
      { front: 'Who was Israel’s first king?', back: 'Saul' },
      { front: 'Which king was “a man after God’s own heart”?', back: 'David' },
      { front: 'Who built the first temple in Jerusalem?', back: 'Solomon' },
      { front: 'Under whose reign did the kingdom split in two?', back: 'Rehoboam (Solomon’s son) — Jeroboam took the north' },
      { front: 'What were the two kingdoms called?', back: 'Israel (north, 10 tribes) and Judah (south)' },
      { front: 'Which empire conquered the northern kingdom, and when?', back: 'Assyria, 722 BC' },
      { front: 'Which empire destroyed Jerusalem and the temple, and when?', back: 'Babylon, 586 BC' },
      { front: 'Which wicked king of Israel married Jezebel?', back: 'Ahab' },
      { front: 'Which boy king found the Book of the Law and led revival?', back: 'Josiah' },
      { front: 'Which king of Judah was healed and given 15 more years?', back: 'Hezekiah' },
    ],
  },
  {
    key: 'women-of-the-bible',
    title: 'Women of the Bible',
    kind: 'fact',
    level: 'intermediate',
    description: 'The women God used to carry the story forward.',
    cards: [
      { front: 'Who said “Where you go, I will go” to her mother-in-law Naomi?', back: 'Ruth' },
      { front: 'Which queen risked her life “for such a time as this”?', back: 'Esther' },
      { front: 'Who was the only female judge of Israel named in Scripture?', back: 'Deborah' },
      { front: 'Who prayed for a son and dedicated Samuel to the Lord?', back: 'Hannah' },
      { front: 'Which woman of Jericho hid the Israelite spies?', back: 'Rahab' },
      { front: 'Who laughed when told she would bear a son at ninety?', back: 'Sarah' },
      { front: 'Who was the first to see the risen Jesus?', back: 'Mary Magdalene' },
      { front: 'Which sisters of Bethany were close friends of Jesus?', back: 'Mary and Martha' },
      { front: 'Which seller of purple cloth became Europe’s first recorded convert?', back: 'Lydia (Acts 16)' },
      { front: 'Which wife-and-husband team taught Apollos the way of God more accurately?', back: 'Priscilla and Aquila' },
    ],
  },
  {
    key: 'names-of-jesus',
    title: 'Names & Titles of Jesus',
    kind: 'fact',
    level: 'intermediate',
    description: 'Who Jesus says he is — name by name.',
    cards: [
      { front: 'What does “Immanuel” mean?', back: '“God with us” (Matthew 1:23)' },
      { front: 'What does “Christ” (Messiah) mean?', back: '“The Anointed One”' },
      { front: 'Who called Jesus “the Lamb of God who takes away the sin of the world”?', back: 'John the Baptist' },
      { front: '“I am the ____ of life” — the crowd had just been fed.', back: 'Bread (John 6:35)' },
      { front: '“I am the good ____ — he lays down his life for the sheep.”', back: 'Shepherd (John 10:11)' },
      { front: '“I am the ____ and the life” — said before raising Lazarus.', back: 'Resurrection (John 11:25)' },
      { front: '“I am the way, the ____, and the life.”', back: 'Truth (John 14:6)' },
      { front: '“I am the true ____; my Father is the farmer.”', back: 'Vine (John 15:1)' },
      { front: 'What title did Jesus use for himself most often in the Gospels?', back: 'The Son of Man' },
      { front: 'In Revelation, Jesus is “the ____ and the Omega.”', back: 'Alpha — the beginning and the end' },
      { front: 'What is Jesus called in John 1:1?', back: 'The Word — who was with God, and was God' },
    ],
  },
  {
    key: 'sermon-on-mount',
    title: 'The Sermon on the Mount',
    kind: 'fact',
    level: 'intermediate',
    description: 'Jesus’ greatest sermon — Matthew 5–7.',
    cards: [
      { front: 'Where in the Bible is the Sermon on the Mount?', back: 'Matthew chapters 5–7' },
      { front: '“Blessed are the poor in spirit, for theirs is…”', back: '…the Kingdom of Heaven' },
      { front: '“Blessed are the meek, for they shall…”', back: '…inherit the earth' },
      { front: '“Blessed are the peacemakers, for they shall be called…”', back: '…children of God' },
      { front: 'What two images did Jesus use for his disciples’ influence in the world?', back: 'Salt of the earth and light of the world' },
      { front: 'What prayer did Jesus teach in the middle of the sermon?', back: 'The Lord’s Prayer (Matthew 6)' },
      { front: 'What is the “golden rule”?', back: 'Do to others what you would have them do to you (Matthew 7:12)' },
      { front: 'What did Jesus point to when teaching “do not worry”?', back: 'The birds of the air and the lilies of the field' },
      { front: 'Instead of “an eye for an eye,” Jesus said to…', back: 'Turn the other cheek' },
      { front: 'How does the sermon end?', back: 'The wise and foolish builders — hearing AND doing his words' },
    ],
  },

  // --- Advanced ----------------------------------------------------------------
  {
    key: 'prophets',
    title: 'The Prophets',
    kind: 'fact',
    level: 'advanced',
    description: 'Major, minor, and the fiery ones in between.',
    cards: [
      { front: 'Name the four “major prophets.”', back: 'Isaiah, Jeremiah, Ezekiel, Daniel' },
      { front: 'How many “minor prophets” are there?', back: 'Twelve — Hosea through Malachi' },
      { front: 'Which prophet was told to marry the unfaithful Gomer?', back: 'Hosea — a picture of God’s love for unfaithful Israel' },
      { front: 'Which prophet saw the valley of dry bones come to life?', back: 'Ezekiel (chapter 37)' },
      { front: 'Which chapter of Isaiah describes the suffering servant?', back: 'Isaiah 53' },
      { front: 'Who is called “the weeping prophet”?', back: 'Jeremiah' },
      { front: 'Which prophet never died but was taken up in a whirlwind?', back: 'Elijah' },
      { front: 'Who received a double portion of Elijah’s spirit?', back: 'Elisha' },
      { front: 'On what mountain did Elijah face the prophets of Baal?', back: 'Mount Carmel' },
      { front: 'Which prophet ran from God’s call to Nineveh?', back: 'Jonah' },
      { front: 'Which shepherd from Tekoa prophesied “let justice roll down like waters”?', back: 'Amos' },
      { front: 'Which prophet interpreted dreams in Babylon’s court?', back: 'Daniel' },
    ],
  },
  {
    key: 'covenants',
    title: 'Covenants of the Bible',
    kind: 'fact',
    level: 'advanced',
    description: 'The promises that structure the whole story.',
    cards: [
      { front: 'What sign sealed God’s covenant with Noah?', back: 'The rainbow — never again a flood to destroy the earth' },
      { front: 'What three things did God promise Abraham?', back: 'Land, countless descendants, and blessing for all nations' },
      { front: 'What was the sign of the Abrahamic covenant?', back: 'Circumcision' },
      { front: 'Where was the Mosaic covenant given, and what was its heart?', back: 'Mount Sinai — the Law, with Israel as God’s treasured possession' },
      { front: 'What did God promise David in 2 Samuel 7?', back: 'A house and throne established forever — fulfilled in Christ' },
      { front: 'Which prophet foretold a “new covenant” written on hearts?', back: 'Jeremiah (31:31–34)' },
      { front: 'When did Jesus announce the new covenant?', back: 'At the Last Supper — “this cup is the new covenant in my blood”' },
      { front: 'Which letter argues at length that the new covenant is better than the old?', back: 'Hebrews' },
    ],
  },
  {
    key: 'pauls-journeys',
    title: 'Paul: Life & Letters',
    kind: 'fact',
    level: 'advanced',
    description: 'The apostle to the Gentiles, from Damascus to Rome.',
    cards: [
      { front: 'On the road to which city was Paul converted?', back: 'Damascus' },
      { front: 'What was Paul’s name before his conversion — and his tribe?', back: 'Saul, of the tribe of Benjamin' },
      { front: 'What trade did Paul work to support himself?', back: 'Tentmaking' },
      { front: 'Who accompanied Paul on his first missionary journey?', back: 'Barnabas (with John Mark, who turned back)' },
      { front: 'Over whom did Paul and Barnabas part ways?', back: 'John Mark — Paul later called him “useful to me” (2 Tim 4:11)' },
      { front: 'Name the four “prison epistles.”', back: 'Ephesians, Philippians, Colossians, Philemon' },
      { front: 'Which letter contains the great “love chapter”?', back: '1 Corinthians (chapter 13)' },
      { front: 'Which two letters argue most fiercely for justification by faith?', back: 'Romans and Galatians' },
      { front: 'Which physician traveled with Paul and wrote two NT books?', back: 'Luke (Luke and Acts)' },
      { front: 'Where does the book of Acts leave Paul?', back: 'Under house arrest in Rome, preaching unhindered' },
      { front: 'Before which crowd did Paul say “I appeal to Caesar”?', back: 'Festus’ court (Acts 25)' },
    ],
  },
  {
    key: 'feasts-israel',
    title: 'The Feasts of Israel',
    kind: 'fact',
    level: 'advanced',
    description: 'The calendar God gave — and what each feast remembers.',
    cards: [
      { front: 'What deliverance does Passover remember?', back: 'The exodus — the Lamb’s blood spared Israel’s firstborn in Egypt' },
      { front: 'What must be removed from the house during the Feast of Unleavened Bread?', back: 'Leaven (yeast)' },
      { front: 'Pentecost falls how many days after Passover — and what happened then in Acts 2?', back: 'Fifty; the Holy Spirit came upon the church' },
      { front: 'What is the most solemn day of Israel’s year?', back: 'The Day of Atonement (Yom Kippur)' },
      { front: 'Who entered the Most Holy Place on the Day of Atonement — and how often?', back: 'Only the high priest, once a year, with blood' },
      { front: 'During which feast does Israel live in shelters — and why?', back: 'Tabernacles (Booths) — remembering the wilderness years' },
      { front: 'Which feast begins with the blowing of trumpets?', back: 'The Feast of Trumpets (Rosh Hashanah)' },
      { front: 'Which festival celebrates the rescue told in Esther?', back: 'Purim' },
      { front: 'Which weekly observance is rooted in creation itself?', back: 'The Sabbath — God rested the seventh day' },
    ],
  },
  {
    key: 'seven-churches',
    title: 'The Seven Churches of Revelation',
    kind: 'fact',
    level: 'advanced',
    description: 'Christ’s letters to the churches of Asia (Revelation 2–3).',
    cards: [
      { front: 'Who wrote down Revelation, and where?', back: 'John, exiled on the island of Patmos' },
      { front: 'Which church had “left its first love”?', back: 'Ephesus' },
      { front: 'Which church was poor yet called rich, and told to be faithful unto death?', back: 'Smyrna' },
      { front: 'Which church dwelt “where Satan’s throne is”?', back: 'Pergamum' },
      { front: 'Which church tolerated “that woman Jezebel”?', back: 'Thyatira' },
      { front: 'Which church had a reputation of being alive but was dead?', back: 'Sardis' },
      { front: 'Which church was given an open door no one can shut?', back: 'Philadelphia' },
      { front: 'Which church was lukewarm — neither hot nor cold?', back: 'Laodicea' },
      { front: 'What does Jesus say he does to those he loves (to Laodicea)?', back: '“Those whom I love, I reprove and chasten” — and he stands at the door and knocks' },
    ],
  },
  {
    key: 'tabernacle-temple',
    title: 'Tabernacle & Temple',
    kind: 'fact',
    level: 'advanced',
    description: 'Where God met his people — from tent to temple.',
    cards: [
      { front: 'What three items does Hebrews say were associated with the ark?', back: 'The stone tablets, a jar of manna, and Aaron’s rod that budded' },
      { front: 'What sat on top of the ark of the covenant?', back: 'The mercy seat, flanked by two cherubim' },
      { front: 'What separated the Holy Place from the Most Holy Place?', back: 'The veil (curtain)' },
      { front: 'What happened to that veil when Jesus died?', back: 'It tore in two, from top to bottom' },
      { front: 'What was the seven-branched lampstand called?', back: 'The menorah' },
      { front: 'Who built the first temple — and who destroyed it?', back: 'Solomon built it; Babylon destroyed it (586 BC)' },
      { front: 'Under whose leadership was the temple rebuilt after exile?', back: 'Zerubbabel (with prophets Haggai and Zechariah urging it on)' },
      { front: 'Which king lavishly expanded the second temple in Jesus’ day?', back: 'Herod the Great' },
      { front: 'What did the bronze basin (laver) provide for the priests?', back: 'Water for washing before serving' },
      { front: 'In the New Testament, what is called God’s temple now?', back: 'Believers — individually and together (1 Cor 3:16, 6:19)' },
    ],
  },
];

function makeCard(c: PresetCard, now: number): Card {
  return { id: uid('cd_'), front: c.front, back: c.back, ref: c.ref, box: 1, due: now, reviews: 0, createdAt: now };
}

/** Materialise a preset into an owned deck with fresh ids + fresh SRS state. */
export function presetToDeck(p: PresetDeck, now: number): Deck {
  return {
    id: uid('dk_'),
    title: p.title,
    description: p.description,
    kind: p.kind,
    createdAt: now,
    cards: p.cards.map((c) => makeCard(c, now)),
  };
}
